<?php
/**
 * ConsignmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\ElectioClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Accounts
 *
 * This API allows to to manage users (accounts) within Electio, including retrieving and updating account details.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ChrisHemmings\ElectioClient;

use \ChrisHemmings\ElectioClient\Configuration;
use \ChrisHemmings\ElectioClient\ApiClient;
use \ChrisHemmings\ElectioClient\ApiException;
use \ChrisHemmings\ElectioClient\ObjectSerializer;

/**
 * ConsignmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ChrisHemmings\ElectioClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConsignmentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addPackageToConsignment
     *
     * .
     *
     */
    public function testAddPackageToConsignment()
    {

    }

    /**
     * Test case for addPackagesToAConsignment
     *
     * .
     *
     */
    public function testAddPackagesToAConsignment()
    {

    }

    /**
     * Test case for cancelAConsignment
     *
     * .
     *
     */
    public function testCancelAConsignment()
    {

    }

    /**
     * Test case for createANewConsignment
     *
     * .
     *
     */
    public function testCreateANewConsignment()
    {

    }

    /**
     * Test case for deAllocateTheSpecifiedConsignment
     *
     * .
     *
     */
    public function testDeAllocateTheSpecifiedConsignment()
    {

    }

    /**
     * Test case for getACountOfConsignments
     *
     * .
     *
     */
    public function testGetACountOfConsignments()
    {

    }

    /**
     * Test case for getASummaryByCarrierInTheDatePeriod
     *
     * .
     *
     */
    public function testGetASummaryByCarrierInTheDatePeriod()
    {

    }

    /**
     * Test case for getASummaryOfConsignmentsInDatePeriod
     *
     * .
     *
     */
    public function testGetASummaryOfConsignmentsInDatePeriod()
    {

    }

    /**
     * Test case for getASummaryOfLatePackagesInTheDatePeriod
     *
     * .
     *
     */
    public function testGetASummaryOfLatePackagesInTheDatePeriod()
    {

    }

    /**
     * Test case for getCustomerManifestByReference
     *
     * .
     *
     */
    public function testGetCustomerManifestByReference()
    {

    }

    /**
     * Test case for getCustomsDocuments
     *
     * .
     *
     */
    public function testGetCustomsDocuments()
    {

    }

    /**
     * Test case for getManifests
     *
     * .
     *
     */
    public function testGetManifests()
    {

    }

    /**
     * Test case for getMultipleConsignmentDetails
     *
     * .
     *
     */
    public function testGetMultipleConsignmentDetails()
    {

    }

    /**
     * Test case for getTheSpecifiedConsignmentDetails
     *
     * .
     *
     */
    public function testGetTheSpecifiedConsignmentDetails()
    {

    }

    /**
     * Test case for getTheSpecifiedConsignmentDetailsByClientReference
     *
     * .
     *
     */
    public function testGetTheSpecifiedConsignmentDetailsByClientReference()
    {

    }

    /**
     * Test case for getTheSpecifiedConsignmentDetailsWithMetadata
     *
     * .
     *
     */
    public function testGetTheSpecifiedConsignmentDetailsWithMetadata()
    {

    }

    /**
     * Test case for getTheStatusOfTheSpecifiedConsignment
     *
     * .
     *
     */
    public function testGetTheStatusOfTheSpecifiedConsignment()
    {

    }

    /**
     * Test case for getTheStatusOfTheSpecifiedConsignmentSByClientReference
     *
     * .
     *
     */
    public function testGetTheStatusOfTheSpecifiedConsignmentSByClientReference()
    {

    }

    /**
     * Test case for manifestConsignments
     *
     * .
     *
     */
    public function testManifestConsignments()
    {

    }

    /**
     * Test case for removePackageFromConsignment
     *
     * .
     *
     */
    public function testRemovePackageFromConsignment()
    {

    }

    /**
     * Test case for updateConsignmentDetails
     *
     * .
     *
     */
    public function testUpdateConsignmentDetails()
    {

    }

    /**
     * Test case for updateConsignmentDetailsAlternativeRoute
     *
     * .
     *
     */
    public function testUpdateConsignmentDetailsAlternativeRoute()
    {

    }

}
